parser: "@typescript-eslint/parser"

parserOptions:
  sourceType: "module"
  ecmaVersion: 2022

ignorePatterns:
  - "dist/*"
  - "**/*.js"
  - "**/*.d.ts"

plugins:
  - "deprecation"

extends:
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
